esudo: false
#branches:
#  only:
#  - master
#  - develop
language: node_js
node_js:
- '7'
before_install:
- 'pwd && ls -als'
- npm -g install npm@latest
install:
- 'pwd && ls -als'
before_script:
- 'pwd && ls -als'
- 'npm install'
- 'npm run package-linux'
script:
- 'npm run lint'
- 'npm run build'
after_success:
- 'pwd && ls -als'
- 'ls dist'
after_failure:
- 'pwd && ls -als'
