esudo: false
#branches:
#  only:
#  - master
#  - develop
language: node_js
node_js:
- '7'
before_install:
- 'pwd && ls -als'
- npm -g install npm@latest
install:
- 'pwd && ls -als'
before_script:
- 'pwd && ls -als'
- 'npm install'
script:
- 'npm run lint'
- 'npm run build'
- 'npm run package-linux' # https://github.com/electron-userland/electron-builder/issues/504#issuecomment-326737539
after_success:
- 'pwd && ls -als'
- 'ls dist'
after_failure:
- 'pwd && ls -als'
